import 'package:flutter/widgets.dart';

// Icônes Phosphor (phosphoricons.com, licence MIT) — polices embarquées dans assets/fonts.
class AppIcons {
  static const _regular = 'PhosphorRegular';
  static const _bold = 'PhosphorBold';
  static const _fill = 'PhosphorFill';

  static const IconData arrowClockwiseBold = IconData(0xe036, fontFamily: _bold);
  static const IconData arrowLeft = IconData(0xe058, fontFamily: _regular);
  static const IconData arrowRightBold = IconData(0xe06c, fontFamily: _bold);
  static const IconData bicycle = IconData(0xe0d6, fontFamily: _regular);
  static const IconData buildings = IconData(0xe102, fontFamily: _regular);
  static const IconData car = IconData(0xe112, fontFamily: _regular);
  static const IconData caretDownBold = IconData(0xe136, fontFamily: _bold);
  static const IconData checkBold = IconData(0xe182, fontFamily: _bold);
  static const IconData clockCounterClockwiseBold = IconData(0xe1a0, fontFamily: _bold);
  static const IconData clockCounterClockwise = IconData(0xe1a0, fontFamily: _regular);
  static const IconData houseFill = IconData(0xe2c2, fontFamily: _fill);
  static const IconData house = IconData(0xe2c2, fontFamily: _regular);
  static const IconData lockSimple = IconData(0xe308, fontFamily: _regular);
  static const IconData motorcycle = IconData(0xe80a, fontFamily: _regular);
  static const IconData packageBold = IconData(0xe390, fontFamily: _bold);
  static const IconData packageFill = IconData(0xe390, fontFamily: _fill);
  static const IconData package = IconData(0xe390, fontFamily: _regular);
  static const IconData pencilSimple = IconData(0xe3b4, fontFamily: _regular);
  static const IconData phone = IconData(0xe3b8, fontFamily: _regular);
  static const IconData phoneFill = IconData(0xe3b8, fontFamily: _fill);
  static const IconData signOut = IconData(0xe42a, fontFamily: _regular);
  static const IconData starBold = IconData(0xe46a, fontFamily: _bold);
  static const IconData starFill = IconData(0xe46a, fontFamily: _fill);
  static const IconData star = IconData(0xe46a, fontFamily: _regular);
  static const IconData thumbsUpFill = IconData(0xe48e, fontFamily: _fill);
  static const IconData userFill = IconData(0xe4c2, fontFamily: _fill);
  static const IconData user = IconData(0xe4c2, fontFamily: _regular);
  static const IconData wallet = IconData(0xe68a, fontFamily: _regular);
  static const IconData whatsappLogoFill = IconData(0xe5d0, fontFamily: _fill);
  static const IconData wifiSlash = IconData(0xe4f2, fontFamily: _regular);
  static const IconData x = IconData(0xe4f6, fontFamily: _regular);
  static const IconData deviceMobile = IconData(0xe1e0, fontFamily: _regular);
  static const IconData deviceMobileSlash = IconData(0xee46, fontFamily: _regular);
  static const IconData magnifyingGlass = IconData(0xe30c, fontFamily: _regular);
  static const IconData plusBold = IconData(0xe3d4, fontFamily: _bold);
  static const IconData prohibit = IconData(0xe3de, fontFamily: _regular);
  static const IconData trash = IconData(0xe4a6, fontFamily: _regular);
  static const IconData users = IconData(0xe4d6, fontFamily: _regular);
  static const IconData bell = IconData(0xe0ce, fontFamily: _regular);
  static const IconData bellFill = IconData(0xe0ce, fontFamily: _fill);
  static const IconData caretRight = IconData(0xe13a, fontFamily: _regular);
  static const IconData flag = IconData(0xe244, fontFamily: _regular);
  static const IconData flagFill = IconData(0xe244, fontFamily: _fill);
  static const IconData gearSix = IconData(0xe272, fontFamily: _regular);
  static const IconData gearSixFill = IconData(0xe272, fontFamily: _fill);
  static const IconData hourglass = IconData(0xe2b2, fontFamily: _regular);
  static const IconData mapPin = IconData(0xe316, fontFamily: _regular);
  static const IconData shieldCheck = IconData(0xe40c, fontFamily: _regular);
  static const IconData usersFill = IconData(0xe4d6, fontFamily: _fill);
  static const IconData warning = IconData(0xe4e0, fontFamily: _regular);
  static const IconData mapPinFill = IconData(0xe316, fontFamily: _fill);
  static const IconData whatsappLogo = IconData(0xe5d0, fontFamily: _regular);
  static const IconData camera = IconData(0xe10e, fontFamily: _regular);
}
